VTN-29799, Add a new method ProduceManualPartition to produce msg to a partition
veritone/go-messaging-lib pull request #68
Opened 2019-09-20 04:48 UTC by cantv6605-seta

Ticket: https://steel-ventures.atlassian.net/browse/VTN-29799

2019-09-20 07:22 UTC, tnguyen-veri requested changes
All functional changes must have unit tests or a valid reason why unit tests are not needed.

2019-09-20 20:21 UTC, cantv6605-seta commented
> All functional changes must have unit tests or a valid reason why unit tests are not needed.

Thanks for your comment. I updated the code.

2019-10-24 15:50 UTC, cantv6605-seta commented
@tnguyen-veri Can you help to merge this one? The main change was merged!
Thanks!

2019-10-24 18:34 UTC, tnguyen-veri approved these changes

2019-10-24 18:34 UTC, merged